import { Router } from "express";
const router = Router();
import * as clinicController from "../Controllers/clinicControllers.js";
import {auth} from "../Middleware/auth.js";
import {endPoints} from "../Endpoints/clinicEndpoints.js";
import { roles } from "../Middleware/roles.js";
import { validation } from "../Middleware/validation.js";
import * as validators from "../Validations/clinicValidation.js";
router.post('/', auth(endPoints.createClinic), validation(validators.createClinic), clinicController.createClinic);
router.get('/:id', auth(Object.values(roles)), validation(validators.getClinicById), clinicController.getClinicById);
router.get('/', auth(Object.values(roles)), clinicController.getAllClinics);
router.patch('/:id', auth(endPoints.updateClinic), validation(validators.updateClinic), clinicController.updateClinic);
router.patch('/softDelete/:id', auth(endPoints.softDeleteClinic), validation(validators.softDeleteClinic), clinicController.softDeleteClinic);
router.delete('/forceDelete/:id', auth(endPoints.forceDeleteClinic), validation(validators.forceDeleteClinic), clinicController.forceDeleteClinic);
export default router;